include:
- xcodegens/packages.yml
name: PomodoroApp
configs:
  Debug: debug
  Release: release
schemes:
  Debug:
    build:
      targets:
        PomodoroApp: all
    run:
      config: Debug
    archive:
      config: Debug
  Release:
    build:
      targets:
        PomodoroApp: all
    run:
      config: Release
options:
  defaultConfig: Debug
  deploymentTarget:
    iOS: 16.1
  preGenCommand: swiftgen
settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 5
    MARKETING_VERSION: 1.4
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  PomodoroApp:
    type: application
    platform: iOS
    sources: 
      - path: PomodoroApp
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.redmadrobot.pomodoro
        INFOPLIST_FILE: PomodoroApp/Supporting Files/Info.plist
        OTHER_SWIFT_FLAGS:
          $(inherited)
          -driver-time-compilation
          -Xfrontend -warn-long-function-bodies=250
          -Xfrontend -warn-long-expression-type-checking=250
          -Xfrontend -debug-time-function-bodies
          -Xfrontend -debug-time-expression-type-checking
        DEVELOPMENT_TEAM: 66Q5RW6PQQ
        CODE_SIGN_IDENTITY: iPhone Distribution
        PROVISIONING_PROFILE_SPECIFIER: ROBODORO Distribution
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf 
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
      - target: PomodoroWidgetExtension
      - package: Nivelir
      - package: Sliders
      - package: SnapKit
  PomodoroWidgetExtension:
    type: app-extension
    platform: iOS
    sources: 
      - path: PomodoroWidgetExtension
      - path: PomodoroApp/Common
      - path: PomodoroApp/Resources
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.redmadrobot.pomodoro.widget
        INFOPLIST_FILE: PomodoroWidgetExtension/Supporting Files/Info.plist
        DEVELOPMENT_TEAM: 66Q5RW6PQQ
        CODE_SIGN_IDENTITY: iPhone Distribution
        PROVISIONING_PROFILE_SPECIFIER: ROBODORO Widget Distribution